"""Kurs tablellari yaradildi

Revision ID: 16c68e20b694
Revises: d4bee2353e0f
Create Date: 2021-04-09 04:15:44.975999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16c68e20b694'
down_revision = 'd4bee2353e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('teachers', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('email', sa.VARCHAR(length=100), nullable=True))
    op.drop_table('courses')
    # ### end Alembic commands ###
