"""Muellimler table yaradildi

Revision ID: d4bee2353e0f
Revises: 5bcb18db274b
Create Date: 2021-04-08 23:40:28.098292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4bee2353e0f'
down_revision = '5bcb18db274b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('title', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'title')
    # ### end Alembic commands ###
